### ISSUE TITLE
Can't locate object method "implementation_roles"

### ISSUE THREAD

**Issue by schelcj** [fleetfootmike/MX-AbstractFactory#6]
I keep running into the below error. Not sure if the problem is my code or this module. Is this a known issue?

Can't locate object method "implementation_roles" via package "Moose::Meta::Class" at /home/schelcj/perl5/lib/perl5/MooseX/AbstractFactory.pm line 26

**Comment by xenoterracide** [comment]
can you provide code, or a test that reproduces this? I think I've seen it before but I haven't actively been hacking on this in a while.

**Comment by schelcj** [comment]
I put a copy of the code put here http://ressik.dyndns.org/~schelcj/ thanks

**Comment by xenoterracide** [comment]
The problem is caused by `use Moose`, not sure why off the top of my head. MX::AbstractFactory does import the moose symbols so it's not necessary. remove the `use Moose` and it should work.

I keep considering making this module a simple role, I'm not really sure why it's not ( none of the tests use the meta object directly ) rumor has it was older than roles.

**Comment by schelcj** [comment]
So I added the use Moose when i got a different error but now that seems to have gone away. I'm left with problems with my code at this point. Thanks for the help. One question though; is there a way to ask the factory what are the different implementations?

**Comment by xenoterracide** [comment]
Not to my knowledge.
